In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

pygame 2.1.2 (SDL 2.0.18, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
import numpy as np
from numpy import array
from numpy import argmax

In [4]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model1 = load_model(r'D:\Processed Data\Drowsiness Detection Models\inceptionv3model.h5')
model2 = load_model(r'D:\Processed Data\Drowsiness Detection Models\mobilenetmodel.h5')
models=[]
models.append(model1)
models.append(model2)

In [9]:
#prediction=np.array()
mixer.init()
sound= mixer.Sound(r'D:\Processed Data\alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:        
        
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        prediction1 = model1.predict(eye)
        prediction2 = model2.predict(eye)
        prediction1[0][0]=max(prediction1[0][0],prediction2[0][0])
        prediction1[0][1]=max(prediction1[0][1],prediction2[0][1])
     
        print(prediction1)
        
        if prediction1[0][0]>0.30:
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=3,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>15):
                try:
                    sound.play()
                except:
                    pass
            
        elif prediction1[0][1]>0.90:      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(3) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 34ms/step
[[0.50505507 0.9593269 ]]
1/1 [==============================] - 0s 33ms/step
[[0.9808842 0.2760735]]
1/1 [==============================] - 0s 35ms/step
[[0.27808943 0.98116183]]
1/1 [==============================] - 0s 36ms/step
[[0.9031453  0.09934915]]
1/1 [==============================] - 0s 34ms/step
[[0.65539193 0.68751556]]
1/1 [==============================] - 0s 34ms/step
[[0.9971836  0.18534984]]
1/1 [==============================] - 0s 33ms/step
[[0.06435742 0.9989812 ]]
1/1 [==============================] - 0s 34ms/step
[[0.51274157 0.9984598 ]]
1/1 [==============================] - 0s 35ms/step
[[0.889856  0.8075554]]
1/1 [==============================] - 0s 36ms/step
[[0.04259085 0.9998017 ]]
1/1 [==============================] - 0s 36ms/step
[[0.35096872 0.81986344]]
1/1 [==============================] - 0s 34ms/step
[[0.17663169 0.9999844 ]]
1/1 [==============================] - 0s 35ms/step
[[0.01886472 0.9